spring:
  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  # ğŸš¨ 1. datasource ì„¤ì •ì„ spring ë¸”ë¡ í•˜ìœ„ë¡œ ì´ë™ ğŸš¨
  datasource:
    url: jdbc:h2:mem:portfolio
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ğŸš¨ 2. h2 ì„¤ì •ì„ spring ë¸”ë¡ í•˜ìœ„ë¡œ ì´ë™ ğŸš¨
  h2:
    console:
      enabled: true
      path: /h2-console